Invalidate all cookies after successful password change
NLP-practitioners/reinforz pull request #104
Opened 2022-06-25 15:45 UTC by xImouto

2022-06-25 16:31 UTC, Devorein requested changes

2022-06-25 16:31 UTC, Devorein commented on packages/server/src/middlewares/authorization.ts
> +    if (userFromDb.tokenVersion > tokenVersion) {
This should check for equality

2022-06-25 17:48 UTC, xImouto commented on packages/server/src/models/User.ts
> +    return removeHashedPass(user);
done in latest commit

2022-06-25 17:50 UTC, xImouto commented on packages/server/src/middlewares/authorization.ts
> +    if (userFromDb.tokenVersion > tokenVersion) {
This will throw error if they are both equal. I dont think that should be the case.

2022-06-26 00:52 UTC, Devorein commented on packages/server/src/middlewares/authorization.ts
> +    if (userFromDb.tokenVersion > tokenVersion) {
Sorry I meant it should throw error if they are not equal.

2022-06-26 03:06 UTC, Devorein approved these changes

2022-06-26 03:08 UTC, merged