Create README for discord-bot
NLP-practitioners/reinforz pull request #109
Opened 2022-06-26 14:53 UTC by arionrefat

2022-06-26 15:50 UTC, Devorein requested changes

2022-06-26 15:50 UTC, Devorein commented on packages/discord-bot/README.md
> +  - `types`: Types exported from `@packages/server`
There is nothing named `@packages/server`

2022-06-26 15:50 UTC, Devorein commented on packages/discord-bot/README.md
> +**NOTE** This must be named `.env`
These are server environment variables, not for discord. The ones for discord-bot are
1. `DISCORD_CLIENT_ID`
2. `DISCORD_BOT_TOKEN`
3. `DISCORD_GUILD_ID`

Please explain what each of them do and how to obtain them (via link to an article)

2022-06-26 15:50 UTC, Devorein commented on packages/discord-bot/README.md
> +1. Create a `.env` file with the keys mentioned [here](#environment-variables-development)
Clicking **here** doesn't navigate to the correct place. Please fix this

2022-06-26 15:50 UTC, Devorein commented on packages/discord-bot/README.md
> +**Note** See `.env.test` in the server package directory to see an example environment variables file.
No need to mention this as server and discord-bot environment variables are completely different

2022-06-26 15:50 UTC, Devorein commented on packages/discord-bot/README.md
> +3. After running the above commands the console should show 'Ready, Then you can send command `!users` in Reinforz discord server.
Write a section for the supported commands. Like so
1. `!users`: Show the number to public, private and total users
2. ....

2022-06-26 16:02 UTC, arionrefat commented on packages/discord-bot/README.md
> +  - `types`: Types exported from `@packages/server`
@reinforz/server?

2022-06-26 16:06 UTC, Devorein commented on packages/discord-bot/README.md
> +  - `types`: Types exported from `@packages/server`
Yep, we don't have it linked with `@reinforz/server` yet but that's the plan. So just replace this with `@reinforz/server`

2022-06-27 01:06 UTC, Devorein approved these changes

2022-06-27 01:06 UTC, merged